### ISSUE TITLE
git-bisect support

### ISSUE THREAD

**Issue by famiu** [NeogitOrg/neogit#1209]
**Is your feature request related to a problem? Please describe.**
As far as I'm aware, Neogit has no support for git-bisect (or at least I could not find anything that mentions this in `:help neogit` or in the `?` help popup). This is bothersome for me as git-bisect is a git feature I have to use fairly often, and having no way to do it inside Neogit is annoying. Furthermore, while I have not used Magit in a while, some searching leads me to believe that this is a feature in Magit: https://magit.vc/manual/magit/Bisecting.html.

**Describe the solution you'd like**
Implement git-bisect in Neogit, similar to how Magit does it.

**Describe alternatives you've considered**
Doing it in the command line, which is fine but it's a little annoying since Neogit already implements functionally everything else that I do in Git.

**Additional context**
N/A.

**Comment by CKolkey** [comment]
Yeah, it's on my radar. I'll probably tackle this soon, no worries.

**Comment by CKolkey** [comment]
Alright, initial bisect support added on `nightly` branch! (requires neovim nightly).

`B` to bring up the popup :)

Some notes, since I haven't written docs:
- If you want to pass a specific commit, you can enter it in the prompt, or find it in the log
- If you select a range of commits in the log buffer, it'll use that as the start/end
- Script support isn't built yet

Lemme know if you have any feedback on the UI/functionality.

**Comment by famiu** [comment]
@CKolkey Okay so, one thing I noticed is that it's not currently possible to open bisect from the `?` help popup, maybe that's intentional?

**Comment by CKolkey** [comment]
Ah, forgot to add it there. Good catch. I'll push some updates soon - I think I was checking the ancestry backwards 😅
