### ISSUE TITLE
Stash List Buffer

### ISSUE THREAD

**Issue by TimUntersberger** [NeogitOrg/neogit#21]
### Actions

- [ ] Apply stash
- [ ] Drop stash
- [ ] Create and checkout a new branch from stash

**Comment by AlphabetsAlphabets** [comment]
Hi @TimUntersberger , I would like to implement `list` for stash.

![image](https://github.com/NeogitOrg/neogit/assets/44822875/4b546cba-4d5f-4af7-bf95-4b31f19c37c1)

I dug around source code and saw it already implemented here

https://github.com/NeogitOrg/neogit/blob/c0b1d4dfc8ba6371857868ca7c4d33954cf002fd/lua/neogit/lib/git/stash.lua#L108-L110

But I'm unsure as to how I'm supposed to link everything together. I'm not even sure if the `list` command is for `git stash list`. I did some basic preliminary work in this commit https://github.com/AlphabetsAlphabets/neogit/commit/c9e8b5544286d0c504ee53356f2d0cbf0578cb00

**Comment by CKolkey** [comment]
Right on! So, you've got it right that `git.stash.list()` will give you the raw data you need. To get it all wired up, you'll need to:
- Add the function to the stash popup actions file like you did in your fork, and pass it into the popup builder like all the other actions. In that action you'll open a new buffer, like we do here: https://github.com/NeogitOrg/neogit/blob/master/lua/neogit/popups/log/actions.lua#L36-L40
- Build a new buffer for the stash list. Take a look in https://github.com/NeogitOrg/neogit/tree/master/lua/neogit/buffers for how thats done. It'll have an `init.lua` and `ui.lua` file. 

That's pretty much it at the high level. Here's a reference of how it looks in Magit, in case you're not familiar. 
<img width="867" alt="Screenshot 2024-04-13 at 12 20 24" src="https://github.com/NeogitOrg/neogit/assets/7228095/d2e0068d-16ac-4cee-96ca-32bf087a18ba">

The reflog buffer has right-aligned virtual text, so you can use that as a reference on how to get the timestamp over there.

If you have any other questions, feel free to ping me here :)

Oh, and I'd recommend basing the work on the `nightly` branch. It _probably_ won't be a big deal, since I haven't messed with the stash stuff as far as I recall, but it wouldn't hurt :)

**Comment by AlphabetsAlphabets** [comment]
@CKolkey thanks so much for the guidance 🙏. I'll get to work on this when I can.

**Comment by AlphabetsAlphabets** [comment]
@CKolkey I know you said I can ping you whenever I have questions so I'll do that. I'm only worried it'll get excessive is all :sweat_smile: anyways so here's my question.

I'm wondering how I can get the `list` method to work when at the stash popup when all the options are displayed. I added `actions.list` to the popup builder in `stash/init.lua` but it's greyed out.

![image](https://github.com/NeogitOrg/neogit/assets/44822875/26503657-a18e-40d9-864a-6234e06996a1)

Right now, it's still greyed out. The reason I'm asking is because I'm not sure how I can test if what I've done so far is correct. I'm unsure of how to test my current progress to see if I'm on the right track.

https://github.com/AlphabetsAlphabets/neogit/blob/master/lua/neogit/popups/stash/actions.lua#L56-L58

Here, I'm wondering what's the purpose of the `use` method. I get that I'll need to implement my own `StashListBuffer` but do I need to use it together with `use`? From what I gathered `FuzzyFinderBuffer` is when you want to log a user's keypress for fuzzy finding. I'm thinking I can simply ignore `use` and use `StashListBuffer` instead.

This is the work I've manage to get done so far https://github.com/AlphabetsAlphabets/neogit/commit/ea74fdabbb35b6799054c0fb28b26fef6ce15bb3

**Comment by CKolkey** [comment]
Hey hey - to get it to show up in the popup, you need to pass the function into the builder method as the last argument. Check out the others that have a `action.*` as the last argument.

You won't need to use the `use()` function, thats for CLI related stuff. `list()` is opening a new buffer, so check out the other functions that launch a buffer. The fuzzy finder is an example of that, but you can also check out the log popup for examples :)

**Comment by AlphabetsAlphabets** [comment]
@CKolkey I've been trying to figure out why there are no changes to the UI despite me modifying the source. I'm not sure if I missed what you said or if something weird is going on. Also FYI I'm using [`rocks.nvim`](https://github.com/nvim-neorocks/rocks.nvim) but I don't think that should be an issue.

https://github.com/AlphabetsAlphabets/neogit/blob/master/lua/neogit/popups/stash/init.lua#L31

In here I added `actions.list` to the `action` call. But, when I restart Neogit, the option for `list` is still greyed out.

![image](https://github.com/NeogitOrg/neogit/assets/44822875/96850e1d-6064-438e-8582-f124de2986b9)

I'm not sure if I missed something that you said. In the same file I linked, I deleted the "Transform" section to see if the UI would change but no, it didn't. It is still there.

![image](https://github.com/NeogitOrg/neogit/assets/44822875/13918621-cd00-40f0-8172-ee0ef4fb735b)

```lua
  local p = popup
    .builder()
    :name("NeogitStashPopup")
    :group_heading("Stash")
    :action("z", "both", actions.both)
    :action("i", "index")
    :action("w", "worktree")
    :action("x", "keeping index")
    :action("P", "push", actions.push)
    :new_action_group("Snapshot")
    :action("Z", "both")
    :action("I", "index")
    :action("W", "worktree")
    :action("r", "to wip ref")
    :new_action_group("Use")
    :action("p", "pop", actions.pop)
    :action("a", "apply", actions.apply)
    :action("d", "drop", actions.drop)
    :new_action_group("Inspect")
    -- Only way to add functionality is to add `actions.list` to `stash/actions.lua`
    :action("l", "List", actions.list)
    :action("v", "Show")
    :env({ stash = stash })
    :build()
```

I removed the "Transform" section locally. It isn't pushed.

**Comment by AlphabetsAlphabets** [comment]
I also did some more work to create the workflow for `git stash list` by adding some options to the buffer as well. I can't test it because of the issue mentioned above where changes I make have no effect. The work is done in this commit https://github.com/AlphabetsAlphabets/neogit/commit/0556ef5ff3c83e00bfd613addc46008627102d35

**Comment by CKolkey** [comment]
> I'm not sure if I missed something that you said. In the same file I linked, I deleted the "Transform" section to see if the UI would change but no, it didn't. It is still there.
I'm not sure how rocks works entirely, but make sure it's using the codebase you're editing. A fast way to find out is to stick a `error("I got called")` at the top of a file, and if there's no error... you're not loading that file.

To your other points, we can always add more options to `git stash list` later, for now I'd just get the basic case working. To that point, option 2 would be preferred.

You're right, its because of how the log buffer is implemented, but one of the key things about Magit, and Neogit, is that level of interactivity with _everything_ in the buffers. So, all the popup menus would work the same everywhere, including the stash list. Fortunately, you can more or less just copy that over from the log buffer, since everything using the UI framework represents the data the same way internally. But all of those mapping can be added after you have the UI rendering something, so don't worry about that up front.

😓 I'm afraid I don't really have any tips for dealing with complex codebases besides read, read, read, and find common patterns. `grep`ing for stuff is your friend, I use that a lot. And, mostly, practice. The more you practice familiarizing yourself with different codebases, the easier it gets.

**Comment by AlphabetsAlphabets** [comment]
> I'm not sure how rocks works entirely, but make sure it's using the codebase you're editing. A fast way to find out is to stick a error("I got called") at the top of a file, and if there's no error... you're not loading that file.

Yeah, you're right. For one reason or not another it wasn't being sourced. I managed to fix it by outright editing the files in the install location lol

**Comment by AlphabetsAlphabets** [comment]
@CKolkey I've managed to make decent progress! Now, I'm only confused at building the UI. I got the pieces to create a UI like Magit in your [earlier comment](https://github.com/NeogitOrg/neogit/issues/21#issuecomment-2053603729). I've checked the examples but it doesn't quite click with me. Could you give me an example of how to build the UI?

https://github.com/AlphabetsAlphabets/neogit/commit/0ba8952ec20fc421693e59425b2e7387331b1f7e is the latest commit after everything is setup.

**Comment by CKolkey** [comment]
Sure. You'll pass a `render` key to the buffer constructor like here: https://github.com/NeogitOrg/neogit/blob/fd63c19287cb275ea38d2c85f41ce712a816c160/lua/neogit/buffers/reflog_view/init.lua#L169-L171

Ideally, all state should get passed into the view through this, meaning the view itself shouldn't make any `git.*` calls.

This is a good view example: https://github.com/NeogitOrg/neogit/blob/fd63c19287cb275ea38d2c85f41ce712a816c160/lua/neogit/buffers/reflog_view/ui.lua#L1

You have a top level component, which has cols and rows and text components.

Don't worry about adding stuff to the common ui elements - thats where things move to once I need them in multiple places. For now, you can keep it all encapsulated in the `lua/neogit/buffers/stash_list/ui.lua` file.

**Comment by AlphabetsAlphabets** [comment]
@CKolkey I did all of that.

```lua
M.Stash = Component.new(function(stashes)
  local children = {}
  for _, stash in ipairs(stashes) do
    -- Split raw output as the stash_id is useful later.
    local raw = util.split(stash, ":")
    local stash_id = raw[1] -- stash@{<num>}
    local stash_msg = raw[2] .. ":" .. raw[3] -- WIP on <branch>: <commit> <msg>"
    local entry = row({
      text(stash_id), text(stash_msg)
    })


    table.insert(children, entry)
  end


  return col(children)
```

> Above snippet from [here](https://github.com/AlphabetsAlphabets/neogit/blob/master/lua/neogit/buffers/stash_list_view/ui.lua).

I'm positive I followed the examples well but there is no output.

https://github.com/NeogitOrg/neogit/assets/44822875/c5865dde-c2d6-45b8-97e9-bd20421cc871

**Comment by AlphabetsAlphabets** [comment]
Hey, @CKolkey would you mind helping me with this?

**Comment by CKolkey** [comment]
Try this :)

```diff
diff --git a/lua/neogit/buffers/common.lua b/lua/neogit/buffers/common.lua
index 8979cdfb..a6e5dd8e 100644
--- a/lua/neogit/buffers/common.lua
+++ b/lua/neogit/buffers/common.lua
@@ -219,7 +219,7 @@ M.CommitEntry = Component.new(function(commit, args)
       }, graph, { text(" ") }, ref, { text(commit.subject) }),
       {
         virtual_text = {
-          { " ",                                     "Constant" },
+          { " ", "Constant" },
           {
             util.str_clamp(commit.author_name, 30 - (#commit.rel_date > 10 and #commit.rel_date or 10)),
             "NeogitGraphAuthor",
diff --git a/lua/neogit/buffers/stash_list_view/init.lua b/lua/neogit/buffers/stash_list_view/init.lua
index 78fbbdee..c435c4c0 100644
--- a/lua/neogit/buffers/stash_list_view/init.lua
+++ b/lua/neogit/buffers/stash_list_view/init.lua
@@ -1,8 +1,7 @@
 local Buffer = require("neogit.lib.buffer")
 local config = require("neogit.config")
-local git = require("neogit.lib.git")
+local CommitViewBuffer = require("neogit.buffers.commit_view")
 
-local StashEntry = require("neogit.lib.git.stash")
 local ui = require("neogit.buffers.stash_list_view.ui")
 
 ---@class StashListBuffer
@@ -10,10 +9,9 @@ local ui = require("neogit.buffers.stash_list_view.ui")
 local M = {}
 M.__index = M
 
---- Gets all current stashes
-function M.new()
+function M.new(stashes)
   local instance = {
-    stashes = git.stash.list()
+    stashes = stashes,
   }
 
   setmetatable(instance, M)
@@ -44,11 +42,13 @@ function M:open()
           self:close()
         end,
         ["<enter>"] = function()
-          -- Still looking for how to view a stash
-          -- CommitViewBuffer.new(self.buffer.ui:get_commit_under_cursor(), self.files):open()
+          CommitViewBuffer.new(self.buffer.ui:get_commit_under_cursor()):open()
         end,
-      }
+      },
     },
+    after = function()
+      vim.cmd([[setlocal nowrap]])
+    end,
     render = function()
       return ui.View(self.stashes)
     end,
diff --git a/lua/neogit/buffers/stash_list_view/ui.lua b/lua/neogit/buffers/stash_list_view/ui.lua
index f22eb804..17245338 100644
--- a/lua/neogit/buffers/stash_list_view/ui.lua
+++ b/lua/neogit/buffers/stash_list_view/ui.lua
@@ -1,38 +1,36 @@
 local Ui = require("neogit.lib.ui")
 local Component = require("neogit.lib.ui.component")
+local util = require("neogit.lib.util")
 
 local text = Ui.text
 local col = Ui.col
 local row = Ui.row
 
-local util = require("neogit.lib.util")
-
-local StashEntry = require("neogit.lib.git.stash").StashEntry
-
 local M = {}
 
----Parses output of `git stash list` and splits elements into table
-M.Stash = Component.new(function(stashes)
-  local children = {}
-  for _, stash in ipairs(stashes) do
-    -- Split raw output as the stash_id is useful later.
-    local raw = util.split(stash, ":")
-    local stash_id = raw[1] -- stash@{<num>}
-    local stash_msg = raw[2] .. ":" .. raw[3] -- WIP on <branch>: <commit> <msg>"
-    local entry = row({
-      text(stash_id), text(stash_msg)
-    })
-
-    table.insert(children, entry)
-  end
-
-  return col(children)
+M.Stash = Component.new(function(stash)
+  local label = table.concat({ "stash@{", stash.idx, "}" }, "")
+
+  return col({
+    row({
+      text.highlight("Comment")(label),
+      text(" "),
+      text(stash.message),
+    }, {
+      virtual_text = {
+        { " ", "Constant" },
+        { stash.rel_date, "Special" },
+      },
+    }),
+  }, { oid = label })
 end)
 
 ---@param stashes StashEntry[]
 ---@return table
 function M.View(stashes)
-  return M.Stash(stashes)
+  return util.map(stashes, function(stash)
+    return M.Stash(stash)
+  end)
 end
 
 return M
diff --git a/lua/neogit/lib/git/stash.lua b/lua/neogit/lib/git/stash.lua
index f93096e8..fa2e4f6e 100644
--- a/lua/neogit/lib/git/stash.lua
+++ b/lua/neogit/lib/git/stash.lua
@@ -7,6 +7,7 @@ local M = {}
 
 ---@class StashEntry
 ---@field stash_id string the id of the stash i.e. stash@{7}
+---@field rel_date string relative timestamp
 ---@field message string the message associated with each stash.
 
 local function perform_stash(include)
@@ -129,7 +130,13 @@ function M.register(meta)
     state.stashes.items = util.map(M.list(), function(line)
       local idx, message = line:match("stash@{(%d*)}: (.*)")
 
+      ---@class StashEntry
       return {
+        rel_date = cli.log
+          .max_count(1)
+          .format("%cr")
+          .args("stash@{" .. idx .. "}")
+          .call({ hidden = true }).stdout[1],
         idx = tonumber(idx),
         name = line,
         message = message,
diff --git a/lua/neogit/popups/stash/actions.lua b/lua/neogit/popups/stash/actions.lua
index c51fa59e..8796a4dd 100644
--- a/lua/neogit/popups/stash/actions.lua
+++ b/lua/neogit/popups/stash/actions.lua
@@ -54,9 +54,8 @@ function M.drop(popup)
   use("drop", popup.state.env.stash)
 end
 
---- git stash list
-function M.list(popup)
-  StashListBuffer.new():open()
+function M.list()
+  StashListBuffer.new(git.repo.state.stashes.items):open()
 end
 
 M.rename = operation("stash_rename", function(popup)
-- 
2.44.0

```

**Comment by AlphabetsAlphabets** [comment]
Hi, @CKolkey I submitted your changes and made a PR https://github.com/NeogitOrg/neogit/pull/1280 could you take a look at it? :)
