### ISSUE TITLE
NeogitLogPopup actions beside Log current are failing

### ISSUE THREAD

**Issue by aleprovencio** [NeogitOrg/neogit#258]
### Description

`Log current` is working fine, but `Log HEAD`, `Log all branches` and `Log all references` return error.

### Neovim version

NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5

### Operating system and version

Archlinux

### Steps to reproduce

1. call `:Neogit`
2. hit `L`
3. hit `b` or `a` or `h`

### Expected behavior

normal output

### Actual behavior

E5108: Error executing lua ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: attempt to call global 'error' (a boolean value)
stack traceback:
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:113: in function 'callback'
        ...m/site/pack/packer/start/neogit/lua/neogit/lib/popup.lua:214: in function 'cb'
        .../site/pack/packer/start/neogit/lua/neogit/lib/buffer.lua:298: in function <.../site/pack/packer/start/neogit/lua/neogit/lib/buffer.
lua:297>
        .../packer/start/neogit/lua/neogit/lib/mappings_manager.lua:9: in function 'invoke'
        [string ":lua"]:1: in main chunk

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by WitzHsiao** [comment]
Same issue with the steps but different error message on my Mac OS 11.5.2

E5108: Error executing lua ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...im/site/pack/packer/start/neogit/lua/neogit/lib
/util.lua:124: attempt to get length of local 'str' (a nil value)
stack traceback:
        [C]: in function 'error'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:113: in function 'callback'
        ...m/site/pack/packer/start/neogit/lua/neogit/lib/popup.lua:214: in function 'cb'
        .../site/pack/packer/start/neogit/lua/neogit/lib/buffer.lua:298: in function <.../site/pack/packer/start/neogit/lua/neogit/lib/buffer.lua:297>
        .../packer/start/neogit/lua/neogit/lib/mappings_manager.lua:9: in function 'invoke'
        [string ":lua"]:1: in main chunk

**Comment by ioreshnikov** [comment]
Yep, getting exactly the same stack trace as @WitzHsiao

**Comment by ioreshnikov** [comment]
The offending part is actually the commit header parser in `lua/neogit/popups/log.lua`. It was introduced two months ago by #252, according to `git blame`. I have no idea what's going on otherwise ¯\\\_(ツ)\_/¯

**Comment by chuck-flowers** [comment]
# Description
I did some digging tonight and I've figured out what's causing the issue. I'm not sure what the appropriate fix would be.

The issue is that the new lua pattern only works when a `*` character comes before the word `commit`. It looks like the `Log current` option is the only one that calls `git log` with the `--graph` switch enabled.

What's weird is that if I add the `--graph` switch manually in the code to the other options, they no longer fail, but toggling the `-g` option from the neogit popup in neovim seems to have no effect on whether the command fails without my code changes. That seems to imply that neogit isn't apply the user's toggling of the `-g` option.

As I said at the start, I'm not sure what the appropriate fix is. I just looked at this code base for the first time a few hours ago. I hope somebody who is more familiar with it than I, will be able to use this as a starting point.

## Useful Info
The pattern variable in question can be found [here](https://github.com/TimUntersberger/neogit/blob/9987421e0724ce704d0035f50a7080c677a85d71/lua/neogit/popups/log.lua#L8)
The calls to the GitHub CLI can be found [here](https://github.com/TimUntersberger/neogit/blob/9987421e0724ce704d0035f50a7080c677a85d71/lua/neogit/popups/log.lua#L122-L150)

**Comment by levouh** [comment]
@TimUntersberger any thoughts on a path forward here or where exactly the underlying issue is coming from? I am more than happy to iterate on a PR to help fix the issue, but similarly to @chuck-flowers I have no idea where to even start.

**Comment by levouh** [comment]
The patch to fix this really does seem as simple as:

```patch
diff --git a/lua/neogit/popups/log.lua b/lua/neogit/popups/log.lua
index 2a2ba2a..a86ab14 100644
--- a/lua/neogit/popups/log.lua
+++ b/lua/neogit/popups/log.lua
@@ -120,18 +120,18 @@ function M.create()
     :action("o", "Log other")
     :action("h", "Log HEAD", function(popup)
       local output =
-        git.cli.log.format("fuller").args(unpack(popup:get_arguments())).for_range("HEAD").call_sync()
+        git.cli.log.format("fuller").args("--graph", unpack(popup:get_arguments())).for_range("HEAD").call_sync()
 
       LogViewBuffer.new(parse(output)):open()
     end)
     :new_action_group()
     :action("b", "Log all branches", function(popup)
       local output =
-        git.cli.log.format("fuller").args(unpack(popup:get_arguments())).branches.remotes.call_sync()
+        git.cli.log.format("fuller").args("--graph", unpack(popup:get_arguments())).branches.remotes.call_sync()
       LogViewBuffer.new(parse(output)):open()
     end)
     :action("a", "Log all references", function(popup)
-      local output = git.cli.log.format("fuller").args(unpack(popup:get_arguments())).all.call_sync()
+      local output = git.cli.log.format("fuller").args("--graph", unpack(popup:get_arguments())).all.call_sync()
       LogViewBuffer.new(parse(output)):open()
     end)
     :new_action_group()
```

made infinitely easier by the troubleshooting that @chuck-flowers did. Based on the pattern that is used for `parse` -> `([| *]*)%*([| *]*)commit (%w+)`, we have:

`(`: Start group
  `[| *]*`: A custom capture group of zero-or-more of `|`, ` `, or `*`
`)`: End group
`%*`: A literal `*`
`(`: Start group
  `[| *]*`: Same as above
`)`: End group
`commit`: Literal word commit
` `: Literal space
`(`: Start group
  `%w+`: One-or-more word characters (alphanumeric, i.e. a hash)
`)`: End group

which if you run `git log --graph` (notably on a branch with a lot of branches and merges to it, e.g `main`), makes perfect sense.

---

The issue comes from the fact that the parser seems to be relying on the output with `--graph`, however `output:get_arguments(...)` actually does _not_ include `--graph` even if you turn it on by pressing `-g` in the log popup window.

From what I can tell, this is because in `builder.lua`, we have:

```lua
--@param parse Whether the switch is internal to neogit or should be included in the cli command.
--             If `false` we don't include it in the cli comand.
function M:switch(key, cli, description, enabled, parse)
  if enabled == nil then
    enabled = false
  end
```

and then using the builder, we call it with:

```lua
    :switch("g", "graph", "Show graph", true, false)
```

so `--graph` is _not_ parsed as a "user configurable" option no matter if you turn it on or off. If we change this line to:

```lua
    :switch("g", "graph", "Show graph", true, true)
```

it then also fixes the problem _for the options that are currently broken_.

---

From this, it then seems to me like `--graph` is _not_ intended to be something the user can turn on or off, and is instead something internal to the way that `neogit` wants to parse the output all together. Hence the set of changes then becomes:

```patch
diff --git a/lua/neogit/popups/log.lua b/lua/neogit/popups/log.lua
index 2a2ba2a..471f451 100644
--- a/lua/neogit/popups/log.lua
+++ b/lua/neogit/popups/log.lua
@@ -93,7 +93,6 @@ function M.create()
   local p = popup
     .builder()
     :name("NeogitLogPopup")
-    :switch("g", "graph", "Show graph", true, false)
     :switch("c", "color", "Show graph in color", true, false)
     :switch("d", "decorate", "Show refnames", true)
     :switch("S", "show-signature", "Show signatures", false)
@@ -120,18 +119,18 @@ function M.create()
     :action("o", "Log other")
     :action("h", "Log HEAD", function(popup)
       local output =
-        git.cli.log.format("fuller").args(unpack(popup:get_arguments())).for_range("HEAD").call_sync()
+        git.cli.log.format("fuller").args("--graph", unpack(popup:get_arguments())).for_range("HEAD").call_sync()
 
       LogViewBuffer.new(parse(output)):open()
     end)
     :new_action_group()
     :action("b", "Log all branches", function(popup)
       local output =
-        git.cli.log.format("fuller").args(unpack(popup:get_arguments())).branches.remotes.call_sync()
+        git.cli.log.format("fuller").args("--graph", unpack(popup:get_arguments())).branches.remotes.call_sync()
       LogViewBuffer.new(parse(output)):open()
     end)
     :action("a", "Log all references", function(popup)
-      local output = git.cli.log.format("fuller").args(unpack(popup:get_arguments())).all.call_sync()
+      local output = git.cli.log.format("fuller").args("--graph", unpack(popup:get_arguments())).all.call_sync()
       LogViewBuffer.new(parse(output)):open()
     end)
     :new_action_group()
```

which is still a bit "jank" as we are just hot-patching in switch-style argument literals, so I've thrown together #343. Will see where that takes us.

**Comment by chuck-flowers** [comment]
@levouh I'm glad that what I found was somewhat helpful.

My guess for why the `--graph` option seems to have that difference in behavior regarding CLI-side vs. Neogit-side is that there were plans to eventually be able to show a traditional log view and a graph log view on the neogit side. Neogit will always need to view the log as a graph when parsing, but can choose what format to output the information that it was able to parse.

I'll be eagerly watching the PR that you opened.

**Comment by CKolkey** [comment]
I've... basically rewritten all of this. Feel free to open a new issue.
