### ISSUE TITLE
[feat] Create new branch could default to checking it out as well

### ISSUE THREAD

**Issue by fnune** [NeogitOrg/neogit#519]
**Is your feature request related to a problem? Please describe.**
When I create a new branch, I then need to use `bl` to find it in the list and check it out.

**Describe the solution you'd like**
When I create a new branch, the branch gets checked out automatically.

**Describe alternatives you've considered**
An interactive list like lazygit's branch TUI. Note that an issue exists for that as well https://github.com/TimUntersberger/neogit/issues/289

**Comment by ten3roberts** [comment]
Do you create a new branch using `bc` or any other command.

`bc` should create and checkout a branch

`bn` just creates a branch, which follows the git behaviour `git branch` vs `git checkout -b`

I personally only use `bc` and work is underway to auto deduce the name from a remote branch to make it easier to checkout branches which aren't local

**Comment by fnune** [comment]
If I use `bc` I get a branch selection UI. I don't see a possibility of entering a new branch name there. Maybe I'm missing something?

**Comment by ten3roberts** [comment]
It prompts for a branch to base it on, so that you can create a local branch for an upstream branch.

`bn` creates a new branch based on the current branch.

It is somewhat inconsistent, do you think that `bn` should prompt for the base branch as well, or `bc` should use the current branch (which makes checking out remote branches difficult).

An alternative is to make the `bb` screen auto setup a local branch if you attempt to checkout a remote branch, rather than the current behavior of landing in detached head state

**Comment by CKolkey** [comment]
... I know I pretty much keep saying this, but I overhauled the branch popup and the behaviour is much more straightforward (and pretty much identical to Magit's ux)

Coming soon to a repo near you..!

**Comment by fnune** [comment]
> To the above point, I flipped the order around for bc so first you give it a name, then pick the base. That always annoyed me too.

:+1: 

@CKolkey I've been trying to use your fork but it's very buggy on my setup. Happy to help debug. I was going to post something but Issues are disabled there.

Either way, looking forward to some of that getting upstreamed :tada:

**Comment by CKolkey** [comment]
@fnune oh, really? Yeah, I'd love to know whats going wrong. Lemme see if I can turn issues on over there
