### ISSUE TITLE
Option to use `vim.notify` instead of the built-in system

### ISSUE THREAD

**Issue by calops** [NeogitOrg/neogit#642]
**Is your feature request related to a problem? Please describe.**
Currently, neogit uses its own custom notification system. It's a bit jarring when happening alongside other notifications from other sources that get displayed very differently. It's also not really customizable.

**Describe the solution you'd like**
Use the standard `vim.notify()` interface so that the user can use the notification engine they prefer. At least offering this as an option would go a long way.

**Comment by gegoune** [comment]
You can use `disable_builtin_notifications = true` to disable those builtin notifications. But I do feel like that functionality could be removed. It was added before `vim.notify()` was a thing (from what I remember) and since it would be breaking change it could be bundled with the rest of upcoming breaking changes. :)

**Comment by CKolkey** [comment]
Not opposed to removing it - low priority to me, but PRs are always welcome :)

**Comment by ten3roberts** [comment]
Yes. I would also be ok with removing it.

I'll close this issue for now as using `vim.notify` is currently possible
