### ISSUE TITLE
[Perf] Don't start a new shell per launch

### ISSUE THREAD

**Issue by Sduby22** [NeogitOrg/neogit#678]
I found that `:Neogit` is getting slower when .zshrc/.bashrc expands. Maybe it's because a new shell process is spawned every time neogit launches.

Some tools like nvm, pyenv will make shell startup horribly slow(3~4sec), which will affect Neogit launch time.

Maybe we can consider spawning the git process directly instead of running a new shell process? 

Thanks

**Comment by Sduby22** [comment]
BTW: I saw some issues that said UI freezes on actions like commiting, maybe relevant?

BTW2: few days ago I have a broken zshrc file on my machine, which breaks some Neogit functions, even when I launch Neogit in an existing repo, it still asks me to "initialize a repo".

**Comment by treatybreaker** [comment]
This is because Neogit attempts to detect a git root the instant it starts up over here https://github.com/NeogitOrg/neogit/blob/656b40e78ff39409eacbee8d8b2dbb47667cee68/lua/neogit/lib/git/repository.lua#L54
The above function calls `git_root` immediately.

And over here https://github.com/NeogitOrg/neogit/blob/656b40e78ff39409eacbee8d8b2dbb47667cee68/lua/neogit/lib/git/config.lua#L58

So two things we can do:
1. Defer these root detection calls if possible
2. Explicitly invoke `/bin/sh` in our command creations such that we don't get that shell overhead

**Comment by treatybreaker** [comment]
As far as I can tell we aren't spawning a new shell process, at least not via `process.new:*` invocations.

Jobstart does not run in a shell when passed a list, which is what we're doing so there shouldn't be a underlying shell it uses (which, as best as I can tell, it doesn't).

**Comment by Sduby22** [comment]
Thanks for replying. I rechecked the problem and find that 

1. `vim.fn.system()` will use `$SHELL -c "some command"` to run commands (in my case `fish -c`). 
2. For some reason, `fish -c` will evaluate `config.fish` file (in contrast, `zsh -c` won't evaluate .zshrc). 

I moved the heavy workload of nvm and pyenv to an `if status is-interactive` block and fixed the problem :)

**Comment by CKolkey** [comment]
As an aside, nvm is hot-trash. https://github.com/Schniz/fnm is a lot faster, though I've just started using https://asdf-vm.com/ for everything and haven't had any trouble :)
