### ISSUE TITLE
After opening neogit, the stage color changes to blue

### ISSUE THREAD

**Issue by saikete** [NeogitOrg/neogit#781]
### Description

Remember not having this problem before, I reinstalled my neogit after a few rounds of major updates, but the staged code turns blue when opened, I've tried looking through the community docs, but there isn't a solution

### Neovim version

0.9.1

### Operating system and version

macOS 14.0

### Steps to reproduce

1. Install neogit according to the documentation (copied the default configuration of the documentation
2. :neogit 

### Expected behavior

Consistent with the document display default effect

### Actual behavior

stage is blue
<img width="925" alt="Snipaste_2023-08-25_02-47-26" src="https://github.com/NeogitOrg/neogit/assets/45237450/570ea159-38a0-4154-8385-7656e33e4e9f">

### Minimal config

```Lua
/default/seeting
```

**Comment by CKolkey** [comment]
Probably your colorscheme. Check out `:hi DiffAdd` or (if that's not set) `:hi String`. One of those is probably blue.

You can also open a PR for your colorscheme to support the Neogit highlight groups (found in docs)

**Comment by b0o** [comment]
I'm seeing this too.

![2023-08-24_13-09-28_region](https://github.com/NeogitOrg/neogit/assets/21299126/61d470f5-db1f-45e7-a922-8f9b85a36911)

Here's what my `DiffAdd` and `String` highlight groups look like:

![2023-08-24_13-10-47_region](https://github.com/NeogitOrg/neogit/assets/21299126/5e93ea33-b484-4d1a-9594-4a35f68f2fbd)


![2023-08-24_13-11-11_region](https://github.com/NeogitOrg/neogit/assets/21299126/87b6cad9-d7e0-49e2-8cc8-b185a7793fc7)


Maybe it's due to `gui=reverse` not being handled properly?

**Comment by CKolkey** [comment]
https://github.com/NeogitOrg/neogit/blob/d764b406a1a6f3db13a28bef10e139a09fcc14dd/lua/neogit/lib/hl.lua#L79

We make a good faith effort to build colors off your existing colorscheme, but... it's an imperfect process. Your best bet is proper highlighting: https://github.com/NeogitOrg/neogit/blob/master/doc/neogit.txt#L195

...Short of that, it's pretty trivial to respect `gui=reverse` - lmk if the linked PR is any better.

**Comment by b0o** [comment]
That PR doesn't look quite right, either. The bg color looks right but the fg color doesn't.

![2023-08-24_14-23-15_region](https://github.com/NeogitOrg/neogit/assets/21299126/751c98eb-4084-4729-9ada-e4c9e3f64f96)

I just noticed this happening after updating a bunch of things on my system - I had been on vacation for over a month, so lots of things got updated.

To try narrowing it down, I tested several commits of Neogit going back 1+ months, same issue there too. Leads me to believe this isn't an issue with Neogit, probably with something else in my setup that changed (wasn't my colorscheme, which is custom).

I'll go ahead and define my own highlight groups instead of debugging this further. Thanks for the help, though!

**Comment by saikete** [comment]
Thank you so much! This provided me with very useful information! I have fixed this after configuring the default diffadd
Hope it helps someone who sees it later
<img width="1070" alt="Snipaste_2023-08-25_10-06-21" src="https://github.com/NeogitOrg/neogit/assets/45237450/a07938bb-9be8-4879-a41a-2aae7bcd9fcf">
