### ISSUE TITLE
Log graph is ordered weirdly?

### ISSUE THREAD

**Issue by gollth** [NeogitOrg/neogit#837]
### Description

Hi there,

first of all thanks for this great project! Long term Emacs user switching to nvim just because `neogit` exists =)

I noticed some weird regression compared to Magit in the graph though. Notice neogit log branches (`l b`) on the left vs. magits log branches on the right (`l b`), both with any `-o` setting (all greyed out):

![bug](https://github.com/NeogitOrg/neogit/assets/31999281/5ad91712-ea45-43ea-8f36-123e63a64c93)

Doing `$ git log --branches --remotes --oneline --decorate --graph` yields a similar look as magit. 

![rawgit](https://github.com/NeogitOrg/neogit/assets/31999281/d76746de-61d7-40e1-9d5f-2b90b29144cb)

Is there a specific setting I'm missing in Neogit? I'm quite used to this graph depicition in my workflow and would be sad if I have to change back to emacs just because of this...

Any help appreciated

### Neovim version

NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Ubuntu 20.04

### Steps to reproduce

1. Open neogit in a repo with multiple branches
2. use log branches `l b`
3. See difference to Magit's log branches view

### Expected behavior

That Neogit show same view than Magit

### Actual behavior

See image above

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "NeogitOrg/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by CKolkey** [comment]
Interesting - thanks for the tip. I'll take a look

**Comment by CKolkey** [comment]
Keen eye - I hadn't noticed, but there was a subtle mistake in how we make the graph... I'll see about fixing this tomorrow.

**Comment by gollth** [comment]
That would be great. Out of curiosity, what is the problem?

**Comment by CKolkey** [comment]
So, it's two things.

It has to do with the order of commits that `git log` returns. Turns out, `--graph` will subtly change the order of commits returned. Not all of them, and not by a lot, but.. yeah, different.

This is an issue because we do _two_ CLI calls to build a log-with-graph. One call uses a custom `--format=` with characters that are easy to split on. Importantly, this _wasn't_ passing in `--graph` because when a commit body contains `\n` characters, they're not escaped but rather the graph is prefixed to the line. So to present a clean body, we would either need to scrub the graph from lines that contain it, or what I decided to go with, two separate calls.

This produces two data structures: a table of parsed graph lines, and a table of parsed commit lines. To combine them back together, I'm looping over the graph table, and popping the top of the commit table every time the graph line contains a `*`. This totally works, if you make the assumption that `--graph` _does not_ change the order. But it does. Slightly.

A less subtle bug I uncovered was that I neglected to pass the args like `--branches --remotes` to the _graph` CLI call too. That one is easy to fix. The first issue described above, however, will require rethinking the approach of collating the graph lines with the correct commit. 

My thinking right now is to modify the graph CLI call to include the hash. That should be simple enough to split. I found that including escape characters in the format makes this operation very accurate (`git log --oneline --graph --format=%x1f%H%`). Then, modify the table of commits to be an associative-array instead of a list, with the commit hash as the key.

**Comment by gollth** [comment]
Aha, wow sounds sophisticated. Hope you find a solution for this

**Comment by CKolkey** [comment]
Haha, yeah.. Thanks for raising the issue - I think I have a working solution now.

**Comment by CKolkey** [comment]
Perhaps a better (simpler) way to put it is that when you pass `--graph`, `--topo-order` is implied, instead of the default chronological order. So, since we do separate calls for the graph and the commit data, we need to pass `--topo-order` unless another order is specified.
