### ISSUE TITLE
handle is already closing

### ISSUE THREAD

**Issue by emmanueltouzery** [NeogitOrg/neogit#843]
### Description

I'm sometimes (twice today) getting that issue when committing to git. I'm not sure what's going on... Possibly some sort of race condition?

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

fedora 38

### Steps to reproduce

unfortunately i cannot reproduce at will. it's related to committing...

### Actual behavior

```
".git/COMMIT_EDITMSG" 10L, 299B written
Error executing vim.schedule lua callback: ...vim/site/pack/packer/start/neogit/lua/neogit/process.lua:173: handle 0x557154dcf960 is already closing
stack traceback:
	[C]: in function 'close'
	...vim/site/pack/packer/start/neogit/lua/neogit/process.lua:173: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...vim/site/pack/packer/start/neogit/lua/neogit/process.lua:173: handle 0x557154d679c0 is already closing
stack traceback:
	[C]: in function 'close'
	...vim/site/pack/packer/start/neogit/lua/neogit/process.lua:173: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "NeogitOrg/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by treatybreaker** [comment]
Oh, we need to check if it's already closing. We're calling timer:close() where it is entirely possible it is already closing:
https://github.com/NeogitOrg/neogit/blob/29aaebd5fd2a6ce95537852d45dca1c036ebc49a/lua/neogit/process.lua#L173

This is because we do a `schedule_wrap` on it and then assign the timer to the instance. It's possible that something else also calls `self.timer:close()` before that scheduled function is ran. When it goes to call `close` something else has already called it.

What's not clear to me is the logic within this function:
https://github.com/NeogitOrg/neogit/blob/29aaebd5fd2a6ce95537852d45dca1c036ebc49a/lua/neogit/process.lua#L161

Checks if the current instance timer exists and if it doesn't only *then* does it start a timer. Surely that's not right? This may be the source of some issues with commits not working (maybe?).

I'll take a look and see what I turn up.

**Comment by emmanueltouzery** [comment]
thanks a lot for the superfast response!

**Comment by CKolkey** [comment]
Yeah, really glad you spotted that - I didn't know the nuance of calling that API. Thanks @treatybreaker
