### ISSUE TITLE
Make a video explaining absolutely all available features

### ISSUE THREAD

**Issue by searleser97** [NeogitOrg/neogit#848]
Could you please make a video where you explain all the features that this plugin has ?

It could help all of us to understand how it works, whats is included and what is not.

This could also help PR contributors to consider all possible scenarios of a new feature, which will prevent potential bugs in the future

Specifically I see there is something in the code called "RebaseEditor" and "MergeEditor" but I can't find information about how they look or exactly what they do, I don't want to assume anything.

Thanks

**Comment by CKolkey** [comment]
First off, I love the enthusiasm. Thing is - if _I_ made video's, they'd be crap. Not my thing. However, the good thing is that there are already TONS of videos on how to use Magit, and since we're basically a poor-man's version of that emacs package, it should translate almost perfectly.

I've also been chipping away at finishing the docs, so `:h neogit` _should_ be a good place to check.

But `RebaseEditor`, `MergeEditor`, etc are _internal_ abstractions, so... I wouldn't put them in a video. It's just the buffer-name for when we open up the editor during an interactive rebase, or while editing a merge message. Or the commit message, that's `CommitEditor`. All of them are basically wrappers around this nifty client-server thing we use to trick git into thinking it opened up the `$EDITOR`, when in fact it's just the same instance of neovim. The reason for different names, despite being the same thing, is... config, mostly. It's got a different filetype, so you can do different things to them.

I'm happy to answer any more questions, but I'm going to close this as it's not really an "issue" ;)
