### ISSUE TITLE
Use "F" binding for pulling

### ISSUE THREAD

**Issue by Silex** [NeogitOrg/neogit#985]
Just like in Emacs's magit. It makes sense:

- `f` for fetching.
- `F` for pulling.

So you have the f key for everything "downloadish" about git.

**Comment by Silex** [comment]
@CKolkey: sure, I can set it in the config, but is there a rationale for not using F?

I can understand you think in terms of **p**ull/**P**ull, but any long term Emacs user will tell you that F makes more sense.

Maybe it's just muscle memory tho.

**Comment by CKolkey** [comment]
Honestly, it's from before I took over the project. I agree with the semantic linking between fetching and pulling (since pulling is just a fetch + merge, roughly). At this point, I'm fine with the default as it is, since it's easy enough to customize and would otherwise just be a disruption for people.

And, for what it's worth, I use `F` for the pull popup haha
